
const types = {
  SET_PETITION: 'SET_PETITION',
  SET_PETITION_ERROR: 'SET_PETITION_ERROR',
  SET_PETITION_LINK: 'SET_PETITION_LINK',
  SET_WALLET_ID: 'SET_WALLET_ID',
  ADD_CREDENTIAL_FROM_URL: 'ADD_CREDENTIAL_FROM_URL',
  STORE_ATTRIBUTES: 'STORE_ATTRIBUTES',
};

export default types;
