
const types = {
  SET_PETITION: 'SET_PETITION',
  SET_PETITION_ERROR: 'SET_PETITION_ERROR',
  SET_PETITION_LINK: 'SET_PETITION_LINK',
  SET_WALLET_ID: 'SET_WALLET_ID',
  ADD_CREDENTIAL_FROM_URL: 'ADD_CREDENTIAL_FROM_URL',
  STORE_ATTRIBUTES: 'STORE_ATTRIBUTES',
  LOAD_ATTRIBUTES: 'LOAD_ATTRIBUTES',
  TOGGLE_REQUIRED_ATTRIBUTE: 'TOGGLE_REQUIRED_ATTRIBUTE',
  TOGGLE_OPTIONAL_ATTRIBUTE: 'TOGGLE_OPTIONAL_ATTRIBUTE',
  SIGN_PETITION: 'SIGN_PETITION',
  SIGN_PETITION_ERROR: 'SIGN_PETITION_ERROR',
  SIGN_OUTCOME: 'SIGN_OUTCOME',

};

export default types;
